server {
    listen 80;
 
    server_name YOUR_DOMAIN_OR_IP www.YOUR_DOMAIN_OR_IP;
 
    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/flask-deployment-using-aws/flaskapp.sock;
    }
}
 
